export const ON_MARKER_CLICK = 'ON_MARKER_CLICK';
export const ON_OBLAST_CLICK = 'ON_OBLAST_CLICK';
export const ON_CITY_CLICK = 'ON_CITY_CLICK';
export const ON_ADDRESS_CLICK = 'ON_ADDRESS_CLICK';
export const ON_ZOOM_CHANGED = 'ON_ZOOM_CHANGED';
export const ON_POINT_CLICK = 'ON_POINT_CLICK';
export const GET_REGIONS_DATA = 'GET_REGIONS_DATA';
